module.exports = {
    _readableState: {
    objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
    readable: true,
        domain: null,
    _events: { end: [Function: responseOnEnd] },
    _eventsCount: 1,
        _maxListeners: undefined,
    socket:
    TLSSocket {
    _tlsOptions:
    { pipe: null,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
    _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events:
    { close: [Object],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
            free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener],
        data: [Function: socketOnData] },
    _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle:
    TLSWrap {
        bytesRead: 2129,
            _externalStream: {},
        fd: -1,
            _parent: [Object],
            _parentWrap: undefined,
            _secureContext: [Object],
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
        writeQueueSize: 1,
            onhandshakestart: [Function],
            onhandshakedone: [Function],
            onocspresponse: [Function],
            onerror: [Function] },
    _parent: null,
        _host: 'testing.api.manager.advertima.com',
        _readableState:
    ReadableState {
        objectMode: false,
            highWaterMark: 16384,
            buffer: [Object],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: false,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null },
    readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState:
    WritableState {
        objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object] },
    writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 135,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl:
    TLSWrap {
        bytesRead: 2129,
            _externalStream: {},
        fd: -1,
            _parent: [Object],
            _parentWrap: undefined,
            _secureContext: [Object],
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
        writeQueueSize: 1,
            onhandshakestart: [Function],
            onhandshakedone: [Function],
            onocspresponse: [Function],
            onerror: [Function] },
    _requestCert: true,
        _rejectUnauthorized: true,
        parser:
    HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': null,
            _headers: [],
            _url: '',
            _consumed: false,
            socket: [Circular],
            incoming: [Circular],
            outgoing: [Object],
            maxHeaderPairs: 2000,
            onIncoming: [Function: parserOnIncomingClient] },
    _httpMessage:
        ClientRequest {
        domain: null,
            _events: [Object],
            _eventsCount: 1,
            _maxListeners: undefined,
            output: [],
            outputEncodings: [],
            outputCallbacks: [],
            outputSize: 0,
            writable: true,
            _last: true,
            upgrading: false,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: false,
            sendDate: false,
            _removedHeader: {},
        _contentLength: 0,
            _hasBody: true,
            _trailer: '',
            finished: true,
            _headerSent: true,
            socket: [Circular],
            connection: [Circular],
            _header: 'GET /manifest/json/?token=c317dae3-331b-47b8-b8b5-3a618d011ac6 HTTP/1.1\r\nHost: testing.api.manager.advertima.com\r\nConnection: close\r\n\r\n',
            _headers: [Object],
            _headerNames: [Object],
            _onPendingData: null,
            agent: [Object],
            socketPath: undefined,
            timeout: undefined,
            method: 'GET',
            path: '/manifest/json/?token=c317dae3-331b-47b8-b8b5-3a618d011ac6',
            _ended: false,
            parser: [Object],
            res: [Circular] },
    read: [Function],
        _consuming: true },
    connection:
        TLSSocket {
    _tlsOptions:
    { pipe: null,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
    _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events:
    { close: [Object],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
            free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener],
        data: [Function: socketOnData] },
    _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle:
    TLSWrap {
        bytesRead: 2129,
            _externalStream: {},
        fd: -1,
            _parent: [Object],
            _parentWrap: undefined,
            _secureContext: [Object],
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
        writeQueueSize: 1,
            onhandshakestart: [Function],
            onhandshakedone: [Function],
            onocspresponse: [Function],
            onerror: [Function] },
    _parent: null,
        _host: 'testing.api.manager.advertima.com',
        _readableState:
    ReadableState {
        objectMode: false,
            highWaterMark: 16384,
            buffer: [Object],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: false,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null },
    readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState:
    WritableState {
        objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object] },
    writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 135,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl:
    TLSWrap {
        bytesRead: 2129,
            _externalStream: {},
        fd: -1,
            _parent: [Object],
            _parentWrap: undefined,
            _secureContext: [Object],
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
        writeQueueSize: 1,
            onhandshakestart: [Function],
            onhandshakedone: [Function],
            onocspresponse: [Function],
            onerror: [Function] },
    _requestCert: true,
        _rejectUnauthorized: true,
        parser:
    HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': null,
            _headers: [],
            _url: '',
            _consumed: false,
            socket: [Circular],
            incoming: [Circular],
            outgoing: [Object],
            maxHeaderPairs: 2000,
            onIncoming: [Function: parserOnIncomingClient] },
    _httpMessage:
        ClientRequest {
        domain: null,
            _events: [Object],
            _eventsCount: 1,
            _maxListeners: undefined,
            output: [],
            outputEncodings: [],
            outputCallbacks: [],
            outputSize: 0,
            writable: true,
            _last: true,
            upgrading: false,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: false,
            sendDate: false,
            _removedHeader: {},
        _contentLength: 0,
            _hasBody: true,
            _trailer: '',
            finished: true,
            _headerSent: true,
            socket: [Circular],
            connection: [Circular],
            _header: 'GET /manifest/json/?token=c317dae3-331b-47b8-b8b5-3a618d011ac6 HTTP/1.1\r\nHost: testing.api.manager.advertima.com\r\nConnection: close\r\n\r\n',
            _headers: [Object],
            _headerNames: [Object],
            _onPendingData: null,
            agent: [Object],
            socketPath: undefined,
            timeout: undefined,
            method: 'GET',
            path: '/manifest/json/?token=c317dae3-331b-47b8-b8b5-3a618d011ac6',
            _ended: false,
            parser: [Object],
            res: [Circular] },
    read: [Function],
        _consuming: true },
    httpVersionMajor: 1,
        httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: false,
    headers:
    { date: 'Mon, 09 Oct 2017 13:18:06 GMT',
        'content-type': 'application/json',
        'transfer-encoding': 'chunked',
        connection: 'close',
        server: 'nginx/1.10.3 (Ubuntu)',
        allow: 'GET, HEAD, OPTIONS',
        'x-frame-options': 'SAMEORIGIN',
        vary: 'Accept, Accept-Language, Cookie',
        'content-language': 'en' },
    rawHeaders:
        [ 'Date',
            'Mon, 09 Oct 2017 13:18:06 GMT',
            'Content-Type',
            'application/json',
            'Transfer-Encoding',
            'chunked',
            'Connection',
            'close',
            'Server',
            'nginx/1.10.3 (Ubuntu)',
            'Allow',
            'GET, HEAD, OPTIONS',
            'X-Frame-Options',
            'SAMEORIGIN',
            'Vary',
            'Accept, Accept-Language, Cookie',
            'Content-Language',
            'en' ],
            trailers: {},
    rawTrailers: [],
        upgrade: false,
    url: '',
    method: null,
    statusCode: 200,
    statusMessage: 'OK',
    client:
    TLSSocket {
    _tlsOptions:
    { pipe: null,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
    _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events:
    { close: [Object],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
            free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener],
        data: [Function: socketOnData] },
    _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle:
    TLSWrap {
        bytesRead: 2129,
            _externalStream: {},
        fd: -1,
            _parent: [Object],
            _parentWrap: undefined,
            _secureContext: [Object],
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
        writeQueueSize: 1,
            onhandshakestart: [Function],
            onhandshakedone: [Function],
            onocspresponse: [Function],
            onerror: [Function] },
    _parent: null,
        _host: 'testing.api.manager.advertima.com',
        _readableState:
    ReadableState {
        objectMode: false,
            highWaterMark: 16384,
            buffer: [Object],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: false,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null },
    readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState:
    WritableState {
        objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object] },
    writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 135,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl:
    TLSWrap {
        bytesRead: 2129,
            _externalStream: {},
        fd: -1,
            _parent: [Object],
            _parentWrap: undefined,
            _secureContext: [Object],
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
        writeQueueSize: 1,
            onhandshakestart: [Function],
            onhandshakedone: [Function],
            onocspresponse: [Function],
            onerror: [Function] },
    _requestCert: true,
        _rejectUnauthorized: true,
        parser:
    HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': null,
            _headers: [],
            _url: '',
            _consumed: false,
            socket: [Circular],
            incoming: [Circular],
            outgoing: [Object],
            maxHeaderPairs: 2000,
            onIncoming: [Function: parserOnIncomingClient] },
    _httpMessage:
        ClientRequest {
        domain: null,
            _events: [Object],
            _eventsCount: 1,
            _maxListeners: undefined,
            output: [],
            outputEncodings: [],
            outputCallbacks: [],
            outputSize: 0,
            writable: true,
            _last: true,
            upgrading: false,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: false,
            sendDate: false,
            _removedHeader: {},
        _contentLength: 0,
            _hasBody: true,
            _trailer: '',
            finished: true,
            _headerSent: true,
            socket: [Circular],
            connection: [Circular],
            _header: 'GET /manifest/json/?token=c317dae3-331b-47b8-b8b5-3a618d011ac6 HTTP/1.1\r\nHost: testing.api.manager.advertima.com\r\nConnection: close\r\n\r\n',
            _headers: [Object],
            _headerNames: [Object],
            _onPendingData: null,
            agent: [Object],
            socketPath: undefined,
            timeout: undefined,
            method: 'GET',
            path: '/manifest/json/?token=c317dae3-331b-47b8-b8b5-3a618d011ac6',
            _ended: false,
            parser: [Object],
            res: [Circular] },
    read: [Function],
        _consuming: true },
    _consuming: false,
        _dumped: false,
    req:
    ClientRequest {
    domain: null,
        _events: { prefinish: [Function: requestOnPrefinish] },
    _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
    _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket:
    TLSSocket {
        _tlsOptions: [Object],
            _secureEstablished: true,
            _securePending: false,
            _newSessionPending: false,
            _controlReleased: true,
            _SNICallback: null,
            servername: null,
            npnProtocol: false,
            alpnProtocol: false,
            authorized: true,
            authorizationError: null,
            encrypted: true,
            _events: [Object],
            _eventsCount: 10,
            connecting: false,
            _hadError: false,
            _handle: [Object],
            _parent: null,
            _host: 'testing.api.manager.advertima.com',
            _readableState: [Object],
            readable: true,
            domain: null,
            _maxListeners: undefined,
            _writableState: [Object],
            writable: true,
            allowHalfOpen: false,
            destroyed: false,
            _bytesDispatched: 135,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: undefined,
            _server: null,
            ssl: [Object],
            _requestCert: true,
            _rejectUnauthorized: true,
            parser: [Object],
            _httpMessage: [Circular],
            read: [Function],
            _consuming: true },
    connection:
        TLSSocket {
        _tlsOptions: [Object],
            _secureEstablished: true,
            _securePending: false,
            _newSessionPending: false,
            _controlReleased: true,
            _SNICallback: null,
            servername: null,
            npnProtocol: false,
            alpnProtocol: false,
            authorized: true,
            authorizationError: null,
            encrypted: true,
            _events: [Object],
            _eventsCount: 10,
            connecting: false,
            _hadError: false,
            _handle: [Object],
            _parent: null,
            _host: 'testing.api.manager.advertima.com',
            _readableState: [Object],
            readable: true,
            domain: null,
            _maxListeners: undefined,
            _writableState: [Object],
            writable: true,
            allowHalfOpen: false,
            destroyed: false,
            _bytesDispatched: 135,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: undefined,
            _server: null,
            ssl: [Object],
            _requestCert: true,
            _rejectUnauthorized: true,
            parser: [Object],
            _httpMessage: [Circular],
            read: [Function],
            _consuming: true },
    _header: 'GET /manifest/json/?token=c317dae3-331b-47b8-b8b5-3a618d011ac6 HTTP/1.1\r\nHost: testing.api.manager.advertima.com\r\nConnection: close\r\n\r\n',
        _headers: { host: 'testing.api.manager.advertima.com' },
    _headerNames: { host: 'Host' },
    _onPendingData: null,
        agent:
    Agent {
        domain: null,
            _events: [Object],
            _eventsCount: 1,
            _maxListeners: undefined,
            defaultPort: 443,
            protocol: 'https:',
            options: [Object],
            requests: {},
        sockets: [Object],
            freeSockets: {},
        keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256,
            maxCachedSessions: 100,
            _sessionCache: [Object] },
    socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/manifest/json/?token=c317dae3-331b-47b8-b8b5-3a618d011ac6',
        _ended: false,
        parser:
    HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': null,
            _headers: [],
            _url: '',
            _consumed: false,
            socket: [Object],
            incoming: [Circular],
            outgoing: [Circular],
            maxHeaderPairs: 2000,
            onIncoming: [Function: parserOnIncomingClient] },
    res: [Circular] } }